<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630150637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bareme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, produit VARCHAR(50) NOT NULL, offre VARCHAR(255) NOT NULL, prime NUMERIC(10, 2) NOT NULL, date_effet DATE NOT NULL, date_fin DATE DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE work_hours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, periode VARCHAR(7) NOT NULL, heures NUMERIC(6, 2) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_id INT NOT NULL, saisi_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2E1C6A23414710B ON work_hours (agent_id)');
        $this->addSql('CREATE INDEX IDX_A2E1C6A2B0F809FE ON work_hours (saisi_par_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AGENT_PERIODE ON work_hours (agent_id, periode)');
        $this->addSql('ALTER TABLE work_hours ADD CONSTRAINT FK_A2E1C6A23414710B FOREIGN KEY (agent_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE work_hours ADD CONSTRAINT FK_A2E1C6A2B0F809FE FOREIGN KEY (saisi_par_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE sale ADD prime NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD manager_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649783E3463 FOREIGN KEY (manager_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_8D93D649783E3463 ON "user" (manager_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE work_hours DROP CONSTRAINT FK_A2E1C6A23414710B');
        $this->addSql('ALTER TABLE work_hours DROP CONSTRAINT FK_A2E1C6A2B0F809FE');
        $this->addSql('DROP TABLE bareme');
        $this->addSql('DROP TABLE work_hours');
        $this->addSql('ALTER TABLE sale DROP prime');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649783E3463');
        $this->addSql('DROP INDEX IDX_8D93D649783E3463');
        $this->addSql('ALTER TABLE "user" DROP manager_id');
    }
}
