<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630134108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, n_commande VARCHAR(50) NOT NULL, bascule VARCHAR(50) DEFAULT NULL, domaine VARCHAR(20) NOT NULL, type VARCHAR(50) NOT NULL, offre VARCHAR(255) NOT NULL, porta BOOLEAN NOT NULL, pto BOOLEAN NOT NULL, convergence BOOLEAN NOT NULL, point_de_vente VARCHAR(255) DEFAULT NULL, valeur NUMERIC(10, 2) NOT NULL, statut VARCHAR(20) NOT NULL, motif_rejet TEXT DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_id INT NOT NULL, valide_par_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E54BC0053414710B ON sale (agent_id)');
        $this->addSql('CREATE INDEX IDX_E54BC00525A40043 ON sale (valide_par_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0053414710B FOREIGN KEY (agent_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC00525A40043 FOREIGN KEY (valide_par_id_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0053414710B');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC00525A40043');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE "user"');
    }
}
